### ISSUE TITLE
Spanbert version

### ISSUE THREAD

**Issue by YeDeming** [mandarjoshi90/coref#11]
Hi,

Thanks for your opening your source code!

In your repo, spanbert is finetuned on OntoNotes (http://nlp.cs.washington.edu/pair2vec/spanbert_base.tar.gz) while you said "The non-finetuned version of SpanBERT weights will be released soon." in readme.

In https://github.com/facebookresearch/SpanBERT, there is also a spanbert model. Is the model in facebookresearch's repo finetuned on OntoNotes? Or it is the non-finetuned version?

Thanks,
Deming Ye

**Comment by mandarjoshi90** [comment]
Sorry about the confusion. The version available in this repo has been finetuned on OntoNotes. The facebookresearch link has the original/non-finetuned version. Thanks!
