### ISSUE TITLE
Question about a Independent.

### ISSUE THREAD

**Issue by fairy-of-9** [mandarjoshi90/coref#15]
I have a question about a Independent.

If I use `Independent` and `max_segment_len = 128`, It divide all documents into 128 tokens. After 128 tokens enter BERT, It will make an embedding for them.

In this situation,
(1) Is it looking for a antecedent only within the 128 tokens?
OR
(2) Put all segments in BERT and get embedding for all tokens.
     and after that, Is it looking for a antecedent within all token?

**Comment by mandarjoshi90** [comment]
It's (2). Here's where the segments are being merged.

https://github.com/mandarjoshi90/coref/blob/master/independent.py#L264

**Comment by fairy-of-9** [comment]
Thank you!
