### ISSUE TITLE
What's the configuration that was used to obtain the spanbert_base baseline

### ISSUE THREAD

**Issue by pku-wuwei** [mandarjoshi90/coref#16]
Is it the one in `experiment.conf`? but the paper said setting `max_seq_len` to 128 is always the best for bert_base and spanbert_base.

**Comment by mandarjoshi90** [comment]
The coref paper only details BERT experiments; SpanBERT was released later. For BERT base, 128 works best. SpanBERT can use larger values of `max_seq_len` more effectively. 384/512 both work pretty well.

**Comment by pku-wuwei** [comment]
Thank you for your timely reply. I am trying to reproduce the baseline results of `bert_base` and `spanbert_base` in `ReadMe.md`，are they the same setting as specified in `experiments.conf`?

**Comment by mandarjoshi90** [comment]
Yes. Is there a specific issue you're facing while training the model?

**Comment by pku-wuwei** [comment]
No, everything works just fine right now! Thank you for your patience 👍
