### ISSUE TITLE
Let the world know about you! 

### ISSUE THREAD

**Issue by LifeIsStrange** [mandarjoshi90/coref#2]
Publishing your paper on arxiv is great.
But please, you achieve state of the art results, so publish your result on the World reference for state of the art which is:
Paperswithcode.com

Add your results here
https://paperswithcode.com/task/coreference-resolution

Someone already published your paper
https://paperswithcode.com/paper/bert-for-coreference-resolution-baselines-and

**Comment by mandarjoshi90** [comment]
Thanks.
