### ISSUE TITLE
Possible to generate predictions (but not train a model) on Mac?

### ISSUE THREAD

**Issue by petulla** [mandarjoshi90/coref#20]
Hi,

I tried getting this going on a new macbook pro but installation didn't seem possible. I just wanted to use your pretrained model to make cluster predictions from a set of documents. I'm wondering if this use case is supported yet. It seems like maybe this is windows/linux + GPU only at this point.

**Comment by mandarjoshi90** [comment]
Hi Sam. Unfortunately, this isn't supported (or at least I don't know how to do it). The easiest way would probably be to get a linux machine from a cloud provider

**Comment by petulla** [comment]
@mandarjoshi90 Thanks. Have you talked to the folks behind https://github.com/huggingface/neuralcoref or Huggingface at all? it seems like there's so much overlap between projects.

**Comment by mandarjoshi90** [comment]
Right. Coreference Resolution is a fairly popular problem in NLP, and there are multiple systems which deal with it. This repo contains research code for reproducing results from our paper and is not intended to be a user-facing solution :)
