### ISSUE TITLE
Is jsonlines_to_json.py available?

### ISSUE THREAD

**Issue by fairy-of-9** [mandarjoshi90/coref#24]
I need results of a coreference resolution consisting of an original index (not bert token index).

kentonl's `jsonlines_to_json.py` don't work, because of indices change by bert tokenizer.

Do you have a  `jsonlines_to_json.py` for bert coreference?
or
Do you have an idea about this problem?

Thanks!

**Comment by mandarjoshi90** [comment]
Could you please link the file you're referring to?

**Comment by fairy-of-9** [comment]
sorry, It's not kenlonl's code but my custom code.

Thanks
