### ISSUE TITLE
setup_all check gcc version

### ISSUE THREAD

**Issue by Naman-ntc** [mandarjoshi90/coref#29]
Hi,
Thanks for releasing the code. While running `predict.py` I was getting 
```
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```
I searched and found this [link](https://github.com/charlesq34/pointnet2/issues/48#issuecomment-404482115). It would be nice to either check the GCC version or keep this as a warning in the script to help anyone else stuck here!!

**Comment by jkkummerfeld** [comment]
Thanks, I ran into this problem and the same thing fixed it for me.

**Comment by mandarjoshi90** [comment]
Sorry, I missed this earlier. I'll add a warning to the README. Just so I understand the solution, removing the flag `-D_GLIBCXX_USE_CXX11_ABI=0` from `setup_all.sh` did the trick?

**Comment by jkkummerfeld** [comment]
That's right.

**Comment by rainyrainyguo** [comment]
I removed the flag from ```setup_all.sh``` but still, get the error:
```
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

**Comment by mariaBio** [comment]
Thank you very much for everyone who contributed to the code release.

I am running the software on the SLURM cluster and facing exactly that same issue:
lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./coref_kernels.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

The setup_all.sh has the following line: 
# Linux (pip)
g++ -std=c++11 -shared coref_kernels.cc -o coref_kernels.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2 
(so the flag that was suggested to be removed is not there)
