### ISSUE TITLE
AssertionError in train.py

### ISSUE THREAD

**Issue by fairy-of-9** [mandarjoshi90/coref#3]
Thank you for your comment.

`${data_dir}/*.jsonlines, ${data_dir}/*.v4_gold_conll` were made successfully.

I tried `GPU=0 python train.py train_1`
but, AssertionError occurred in evaluation.

It's my experiments.conf
```
data_dir = data

best {
  # Edit this
  data_dir = data
  model_type = independent
  # Computation limits.
  max_top_antecedents = 50
  max_training_sentences = 5
  top_span_ratio = 0.4
  max_num_speakers = 20
  max_segment_len = 256

  # Learning
  bert_learning_rate = 1e-5
  task_learning_rate = 2e-4
  num_docs = 2802

  # Model hyperparameters.
  dropout_rate = 0.3
  ffnn_size = 1000
  ffnn_depth = 1
  num_epochs = 20
  feature_size = 20
  max_span_width = 30
  use_metadata = true
  use_features = true
  use_segment_distance = true
  model_heads = true
  coref_depth = 2
  coarse_to_fine = true
  fine_grained = true
  use_prior = true

  # Other.
  train_path = train.english.jsonlines
  eval_path = dev.english.jsonlines
  conll_eval_path = dev.english.v4_gold_conll
  single_example = true
  genres = ["bc", "bn", "mz", "nw", "pt", "tc", "wb"]
  eval_frequency = 1000
  report_frequency = 100
  #log_root = ${data_dir}
  log_root = models
  adam_eps = 1e-6
  task_optimizer = adam
}

train_1 = ${best}{
  num_docs = 2802
  bert_learning_rate = 1e-05
  task_learning_rate = 0.0002
  max_segment_len = 128
  ffnn_size = 200
  model_heads = false
  train_path = ${data_dir}/train.english.128.jsonlines
  eval_path = ${data_dir}/dev.english.128.jsonlines
  conll_eval_path = ${data_dir}/dev.english.v4_gold_conll
  max_training_sentences = 5
  bert_config_file = data/cased_L-12_H-768_A-12/bert_config.json
  vocab_file = data/cased_L-12_H-768_A-12/vocab.txt
  tf_checkpoint = data/cased_L-12_H-768_A-12/bert_model.ckpt
  init_checkpoint = data/cased_L-12_H-768_A-12/bert_model.ckpt
}

```

and result
```
I0829 11:00:12.977631 139776037099264 train.py:58] [1000] loss=nan, steps/s=5.96
Loaded 343 eval examples.
2019-08-29 11:00:18.389048: W tensorflow/core/kernels/queue_base.cc:277] _0_padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    eval_summary, eval_f1 = model.evaluate(session, tf_global_step)
  File "/data/BERT-coref/coref/independent.py", line 559, in evaluate
    coref_predictions[example["doc_key"]] = self.evaluate_coref(top_span_starts, top_span_ends, predicted_antecedents, example["clusters"], coref_evaluator)
  File "/data/BERT-coref/coref/independent.py", line 524, in evaluate_coref
    predicted_clusters, mention_to_predicted = self.get_predicted_clusters(top_span_starts, top_span_ends, predicted_antecedents)
  File "/data/BERT-coref/coref/independent.py", line 499, in get_predicted_clusters
    assert i > predicted_index, (i, predicted_index)
AssertionError: (0, 0)

```
Is there anything I missed?

**Comment by mandarjoshi90** [comment]
It looks like your loss is diverging. I'll need more information to be able to help.
1. Were you able to evaluate the pretrained models with the default config? That will ensure that you have the right setup.
2. Did you try training with the default config for base?
3. Do the `jsonlines` files look ok? 
4. Can you post the loss for the first 1000 steps?

**Comment by fairy-of-9** [comment]
I'm using Titan XP.

1.  command : `GPU=0 python evaluate.py bert_base` << default config.
result:
![image](https://user-images.githubusercontent.com/37280914/63909500-d4a71600-ca5d-11e9-9aef-a3c166eeb311.png)

2/4. Result of `GPU=0 python train.py train_bert_base`
![image](https://user-images.githubusercontent.com/37280914/63909232-e0dea380-ca5c-11e9-8a60-f02d277fffad.png)

3. In my opinion, jsonlines files were made successfully.
`{"doc_key": "bc/cctv/00/cctv_0000_0", "sentences": [["[CLS]", "In", "the", "summer", " ...`

**Comment by mandarjoshi90** [comment]
Hmm, the loss is going down so that's good. But I'm not sure why the evaluation is messing up. Could you send me the complete log?

**Comment by fairy-of-9** [comment]
I tried `GPU=0 python evaluate.py bert_base` for the complete log to give you.
`evalute.py` worked well!

and 'train.py' is working!
![image](https://user-images.githubusercontent.com/37280914/63910503-e8547b80-ca61-11e9-8fb2-b21f77278a4b.png)


I don't understand this situation....
Thank you for your comment!!!
