### ISSUE TITLE
Link is down

### ISSUE THREAD

**Issue by resurrection-crisis** [mandarjoshi90/coref#34]
http://nlp.cs.washington.edu/pair2vec/$1.tar.gz

**Comment by mandarjoshi90** [comment]
I'm assuming you got this URL from `./download_pretrained.sh`. It's a shell script and $1 refers to the argument. Please call the script directly, or replace $1 with the argument. So the URL for downloading the spanbert_base model finetuned on coref is:

http://nlp.cs.washington.edu/pair2vec/spanbert_base.tar.gz
