### ISSUE TITLE
Missing path $data_dir/spanbert_base/bert_config.json

### ISSUE THREAD

**Issue by minhlab** [mandarjoshi90/coref#36]
Hi, thanks for the implementation. I'm trying to train my first model but got this error:

```
$ GPU=0 python train.py train_spanbert_base
...
tensorflow.python.framework.errors_impl.NotFoundError: ../output/bert/data/spanbert_base/bert_config.json; No such file or directory
```

`../output/bert/data` is an empty folder before I ran `setup_all.sh` and `setup_training.sh`. Am I missing some step here?

**Comment by mandarjoshi90** [comment]
I'm assuming that you set the $data_dir variable. From what I can tell, `setup_training.sh` must have failed. Might be a good idea to re-run it and check. You could also manually download spanbert if you have everything else setup.
