### ISSUE TITLE
error with requirements.txt

### ISSUE THREAD

**Issue by sushantakpani** [mandarjoshi90/coref#37]
I run: **pip install -r requirements.txt**
Got following error. 

ERROR: mxnet 1.4.0 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.18.1 which is incompatible.
ERROR: bert-embedding 1.0.1 has requirement numpy==1.14.6, but you'll have numpy 1.18.1 which is incompatible.
Installing collected packages: PyYAML, awscli, certifi, jpype1, cython, mmh3, future, pystanforddependencies, soupsieve, beautifulsoup4, cort
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Is the project depend on specific version of packages mentioned or higher version will also work ?**

**Comment by mandarjoshi90** [comment]
I'm not seeing this. Did you try a fresh install with a virtual environment?
