### ISSUE TITLE
Bert Retraining 

### ISSUE THREAD

**Issue by bodasheera** [mandarjoshi90/coref#49]
Hi Mandar , 

While running spanbert large model , if is not able to capture some of words such as Degree . 
The same text if I use other brand like Kurkure it will detect . Can I train coref model with my own dataset .

How do I do it ? I have access to onto notes 5. I'm new in the field on AI . Should I convert my dataset to ontonotes format? How can I train on custom dataset.

**Comment by fairy-of-9** [comment]
Convert your dataset to conll format. (I think It's easiest way)
and convert conll to jsonlines using `minimize.py`
you can see conll format through results of `./setup_training.sh`
