### ISSUE TITLE
OntoNotes Training 

### ISSUE THREAD

**Issue by Hafsa-Masroor** [mandarjoshi90/coref#50]
The Setup for training section says:
`./setup_training.sh <ontonotes/path/ontonotes-release-5.0> $data_dir`

What does this path **<ontonotes/path/ontonotes-release-5.0>** refer? How can I access it?

**Comment by Hafsa-Masroor** [comment]
@mandarjoshi90 Please help for my above concern.

**Comment by mandarjoshi90** [comment]
The OntoNotes corpus is available via LDC.
https://catalog.ldc.upenn.edu/LDC2013T19

**Comment by troublemaker-r** [comment]
@Hafsa-Masroor   
path <ontonotes/path/ontonotes-release-5.0> is ontonotes-release-5.0 dataset path。
First，you need to get the data from the LCD。
