### ISSUE TITLE
finetuning on pytorch model

### ISSUE THREAD

**Issue by HaixiaChai** [mandarjoshi90/coref#52]
Hi Mandar,

I wonder if the model can be finetuned using the pytorch version of BERT? I saw that there are tf_checkpoint and init_checkpoint in the config file. Is it possible to modify them in order to support pytorch BERT models.

**Comment by mandarjoshi90** [comment]
Hi. Just to make sure I understand the question. Do you mean converting a BERT Pytorch checkpoint to TF, and then finetuning with this repo (using TF)? If so, then yes. See 

https://github.com/mandarjoshi90/coref/blob/master/independent.py#L60
