### ISSUE TITLE
Repeated mention Error !!

### ISSUE THREAD

**Issue by sushantakpani** [mandarjoshi90/coref#66]
What do repeated mentions mean in this error? 
"Found too many repeated mentions (> 10) in the response, so refusing to score. Please fix the output"

I checked and found this error message in 'coref/conll-2012/scorer/v8.01/lib/CorScorer.pm'
I am facing this error during the evaluation of validation and test data CONLL 2012 OntoNotes data.

**Comment by mandarjoshi90** [comment]
I'm not sure how I can reproduce this. One way to debug this is to check the input file to the perl script and look at what's going on. If you don't particularly care about the official numbers, you could use the ones produced by the python script instead.

**Comment by sushantakpani** [comment]
> I'm not sure how I can reproduce this. One way to debug this is to check the input file to the perl script and look at what's going on. If you don't particularly care about the official numbers, you could use the ones produced by the python script instead.

Thanks.
