### ISSUE TITLE
Let's improve the state of the art once again, by using it 

### ISSUE THREAD

**Issue by LifeIsStrange** [mandarjoshi90/coref#7]
Hi!
I see you beated state of the art on coreference resolution (which is a fundamental NLP task!!) by using and tuning BERT.

Yet, BERT has been "obscoleted" by XLnet. 
So would you like to be the first to use and fine tune it for coreference resolution just like you did with BERT? That would be very helpful for all those people that needs highly accurate coref.

https://github.com/zihangdai/xlnet

BTW I suggested the same idea to a researcher in dependency/constituency parsing a few weeks ago and they are now number 1 on the paperswithcode.com leaderboards!

**Comment by mandarjoshi90** [comment]
Thanks. Unfortunately, I don't have the bandwidth to do this.

**Comment by LifeIsStrange** [comment]
@mandarjoshi90
Ok, maybe you could try the new best activation function? It should be far less work and can still improve accuracy by a few percents.

https://github.com/digantamisra98/Mish
Anyway those are just suggestions. 
There is also the Ranger Optimizer to try
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

**Comment by LifeIsStrange** [comment]
@mandarjoshi90 is xlnet something that you ambition to experiment in 2021?
The state of the art on coreference resolution has stagnated which is sad
