### ISSUE TITLE
converting predicted (subtoken) output to normal text

### ISSUE THREAD

**Issue by ambernorder** [mandarjoshi90/coref#82]
Hello,

When the model has predicted something the text is tokenized (The "##" in the sentences).
How can you convert this, togehter with the coreference clusters, back to normal text?

**Comment by linguist89** [comment]
If you take a look at the notebook that is linked in the repo's README, you will see there is a section where the author converted the output back to readable English sentences. Work through that code and you will be able to convert your output back to readable text.
