### ISSUE TITLE
Predicting singletons

### ISSUE THREAD

**Issue by ambernorder** [mandarjoshi90/coref#84]
Hi,

Is it possible to predict singletons with this model? 
I trained a model with my own data which contained singletons, but when I predict some text with my model it will only return clusters with at least two mentions. 

Thank you!

**Comment by linguist89** [comment]
Singletons aren't coreferential, so that would just be entity recoginition, wouldn't it? The idea of the coreference resolution is to determine which clusters of words refer to the same real-world entity.
